/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_BIT_RATE 8000000

#define DEFAULT_LOCAL_PORT_RANGE_FIRST 27183

#define DEFAULT_LOCAL_PORT_RANGE_LAST 27199

#define DEFAULT_LOCK_VIDEO_ORIENTATION -1

#define DEFAULT_MAX_SIZE 0

#define HIDPI_SUPPORT

#define NDEBUG

#define PORTABLE

#define PREFIX "/usr/local"

#define SCRCPY_VERSION "1.17"

#undef SERVER_DEBUGGER

#define SERVER_DEBUGGER_METHOD_NEW

#if defined(_WIN64)

typedef long int ssize_t;

#endif

#if defined(WIN32)

typedef int ssize_t;

#endif
typedef short  pid_t;
